GET http://localhost:8080/ 

###

POST http://localhost:8080/auth/login 
Content-Type: application/json

{
    "email" : "faislabdu277@gmail.com",
    "password" : "123"
}

###
GET http://localhost:8080/data/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJlbWFpbCI6ImZhaXNsYWJkdTI3N0BnbWFpbC5jb20ifSwiaWF0IjoxNzM2Mjc5MzY0LCJleHAiOjE3MzYzNjU3NjR9.zcnQUkx3cfV3TYUSG9F9MhCAvje8ePxrT5XPY-v9oZc


###   
PUT http://localhost:8080/data/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMCwiZW1haWwiOiJmaGFiZG8yMUBjaXQuanVzdC5lZHUuam8ifSwiaWF0IjoxNzM2MTk2ODM1LCJleHAiOjE3MzYyODMyMzV9.n7JH3JZ_nYhA9FMGSuntHVdnXWyF4ir7r6Rs15BXABk
Content-Type: application/json

{
    "email": "faislabdu277@gmail.com",
    "user_name": "Faisal999123",
    "fname": "Faisal H ",
    "lname": "Abdo"
}

###

POST http://localhost:8080/auth/request-password-reset 
Content-Type: application/json

{
  "email": "faislabdu277@gmail.com"
}
